package com.fastfilemanager.app;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.Color;import android.net.Uri;import android.view.*;import android.widget.*;import java.io.*;import java.text.*;import java.util.*;

public class MainActivity extends Activity {
 LinearLayout root,list; TextView pathView; boolean showHidden=false; File current; SharedPreferences prefs; final ArrayList<File> selected=new ArrayList<>(); final int REQ_TREE=44;
 @Override public void onCreate(Bundle b){super.onCreate(b);prefs=getSharedPreferences("prefs",0);build();current=getExternalFilesDir(null);showDir(current);}
 TextView tv(String s,int sp){TextView t=new TextView(this);t.setText(s);t.setTextSize(sp);t.setTextColor(Color.DKGRAY);t.setPadding(18,12,18,12);return t;}
 Button btn(String s){Button b=new Button(this);b.setText(s);b.setTextSize(16);b.setMinHeight(110);return b;}
 void build(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(Color.WHITE);
  LinearLayout top=new LinearLayout(this);top.setOrientation(LinearLayout.HORIZONTAL);top.setGravity(Gravity.CENTER_VERTICAL);
  String[] names={"Close","Cut","Copy","Paste","Extract","Compress","Search","Sort","Properties","Tags","Rename Group","Settings"};
  for(String n:names){Button b=btn(n);top.addView(b,new LinearLayout.LayoutParams(220,110));
   if(n.equals("Search"))b.setOnClickListener(v->search()); if(n.equals("Sort"))b.setOnClickListener(v->sortMenu()); if(n.equals("Properties"))b.setOnClickListener(v->propertiesSelected()); if(n.equals("Settings"))b.setOnClickListener(v->settings()); if(n.equals("Compress"))b.setOnClickListener(v->Toast.makeText(this,"Compress: ZIP operation will use the selected files.",Toast.LENGTH_SHORT).show()); if(n.equals("Extract"))b.setOnClickListener(v->Toast.makeText(this,"Extract: select one or more archives.",Toast.LENGTH_SHORT).show()); if(n.equals("Tags"))b.setOnClickListener(v->tagSelected()); if(n.equals("Rename Group"))b.setOnClickListener(v->batchRename()); if(n.equals("Close"))b.setOnClickListener(v->finish());}
  HorizontalScrollView hs=new HorizontalScrollView(this);hs.addView(top);root.addView(hs,new LinearLayout.LayoutParams(-1,120));
  LinearLayout nav=new LinearLayout(this);Button up=btn("↑");up.setOnClickListener(v->{if(current!=null&&current.getParentFile()!=null)showDir(current.getParentFile());});Button usb=btn("USB / HDD");usb.setOnClickListener(v->pickTree());Button fav=btn("★ Favorites");fav.setOnClickListener(v->favorites());Button lib=btn("Library");lib.setOnClickListener(v->library());Button sel=btn("Select All");sel.setOnClickListener(v->selectAll());nav.addView(up);nav.addView(usb);nav.addView(fav);nav.addView(lib);nav.addView(sel);root.addView(nav,new LinearLayout.LayoutParams(-1,120));
  pathView=tv("",17);root.addView(pathView);list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);ScrollView sv=new ScrollView(this);sv.addView(list);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));setContentView(root); }
 void showDir(File f){if(f==null||!f.exists())return;current=f;selected.clear();pathView.setText("📍 "+f.getAbsolutePath());list.removeAllViews();File[] a=f.listFiles();if(a==null)return;Arrays.sort(a,(x,y)->Boolean.compare(!x.isDirectory(),!y.isDirectory()));for(File x:a)if(showHidden||!x.getName().startsWith("."))addItem(x);}
 void addItem(File f){LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);CheckBox cb=new CheckBox(this);cb.setText("");cb.setMinWidth(80);cb.setOnCheckedChangeListener((b,c)->{if(c&&!selected.contains(f))selected.add(f);else selected.remove(f);});TextView icon=tv(iconFor(f),32);TextView name=tv(displayName(f),17);row.addView(cb,new LinearLayout.LayoutParams(85,115));row.addView(icon,new LinearLayout.LayoutParams(80,115));row.addView(name,new LinearLayout.LayoutParams(0,115,1));Button more=btn("⋮");more.setOnClickListener(v->itemMenu(f));row.addView(more,new LinearLayout.LayoutParams(100,115));row.setOnClickListener(v->{if(f.isDirectory())showDir(f);});list.addView(row);}
 String displayName(File f){String tag=prefs.getString("tag_"+f.getAbsolutePath(),"");String mark=tag.isEmpty()?"":"  [#"+tag+"]";return f.getName()+mark+(f.isDirectory()?"":"\n"+size(f.length()));}
 String iconFor(File f){if(f.isDirectory())return "📁";String n=f.getName().toLowerCase();if(n.endsWith(".apk")||n.endsWith(".xapk")||n.endsWith(".apks")||n.endsWith(".aab"))return "📦";if(n.endsWith(".zip")||n.endsWith(".rar")||n.endsWith(".7z"))return "🗜️";if(n.matches(".*\\.(jpg|jpeg|png|webp|gif)$"))return "🖼️";if(n.matches(".*\\.(mp4|mkv|avi|mov)$"))return "🎬";if(n.matches(".*\\.(mp3|wav|flac|ogg)$"))return "🎵";if(n.endsWith(".pdf"))return "📕";if(n.matches(".*\\.(doc|docx)$"))return "📝";if(n.matches(".*\\.(xls|xlsx)$"))return "📊";return "📄";}
 String size(long n){if(n<1024)return n+" B";if(n<1024*1024)return (n/1024)+" KB";if(n<1024L*1024*1024)return (n/1024/1024)+" MB";return (n/1024/1024/1024)+" GB";}
 void itemMenu(File f){String[] a={"Open","Properties","Favorite","Tag","Rename","Delete"};new AlertDialog.Builder(this).setTitle(f.getName()).setItems(a,(d,w)->{if(w==0&&f.isDirectory())showDir(f);else if(w==1)properties(f);else if(w==2)favAdd(f);else if(w==3)tagOne(f);else if(w==4)rename(f);else delete(f);}).show();}
 void selectAll(){selected.clear();File[] a=current.listFiles();if(a!=null)for(File f:a)if(showHidden||!f.getName().startsWith("."))selected.add(f);Toast.makeText(this,"Selected: "+selected.size(),Toast.LENGTH_SHORT).show();}
 void propertiesSelected(){if(selected.size()==1)properties(selected.get(0));else Toast.makeText(this,"Select exactly one item for Properties",Toast.LENGTH_SHORT).show();}
 void properties(File f){String s="Name: "+f.getName()+"\nType: "+(f.isDirectory()?"Folder":iconFor(f))+"\nSize: "+size(f.isDirectory()?folderSize(f):f.length())+"\nPath: "+f.getAbsolutePath()+"\nModified: "+new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date(f.lastModified()));final String txt=s;new AlertDialog.Builder(this).setTitle("Properties").setMessage(s).setPositiveButton("Copy",(d,w)->((android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE)).setPrimaryClip(android.content.ClipData.newPlainText("Properties",txt))).setNegativeButton("Close",null).show();}
 long folderSize(File f){long z=0;File[] a=f.listFiles();if(a!=null)for(File x:a)z+=x.isDirectory()?folderSize(x):x.length();return z;}
 void favAdd(File f){prefs.edit().putString("fav_"+f.getAbsolutePath(),f.getAbsolutePath()).apply();Toast.makeText(this,"Added to Favorites",Toast.LENGTH_SHORT).show();}
 void favorites(){list.removeAllViews();pathView.setText("★ Favorites");for(Map.Entry<String,?> e:prefs.getAll().entrySet())if(e.getKey().startsWith("fav_")){File f=new File(String.valueOf(e.getValue()));if(f.exists())addItem(f);}}
 void library(){list.removeAllViews();pathView.setText("📚 Library");ArrayList<File> all=new ArrayList<>();scan(current,all);all.sort((a,b)->Long.compare(b.lastModified(),a.lastModified()));addSection("New Files",all.subList(0,Math.min(30,all.size())));ArrayList<File> big=new ArrayList<>(all);big.sort((a,b)->Long.compare(b.length(),a.length()));addSection("Big Files",big.subList(0,Math.min(30,big.size())));}
 void addSection(String s,List<File> fs){list.addView(tv(s,21));for(File f:fs)addItem(f);}
 void scan(File f,List<File> out){File[] a=f.listFiles();if(a==null)return;for(File x:a){if(x.isDirectory())scan(x,out);else if(showHidden||!x.getName().startsWith("."))out.add(x);}}
 void search(){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);EditText q=new EditText(this);q.setHint("File or folder name");EditText p=new EditText(this);p.setHint("Optional full path");box.addView(q);box.addView(p);new AlertDialog.Builder(this).setTitle("Search / Go to Path").setView(box).setPositiveButton("Search",(d,w)->{String s=q.getText().toString().toLowerCase();list.removeAllViews();ArrayList<File>a=new ArrayList<>();scan(current,a);for(File f:a)if(f.getName().toLowerCase().contains(s))addItem(f);}).setNeutralButton("Go to Path",(d,w)->goPath(p.getText().toString().isEmpty()?q.getText().toString():p.getText().toString())).setNegativeButton("Cancel",null).show();}
 void goPath(String p){if(p==null||p.trim().isEmpty())return;File f=new File(p.trim());if(f.isFile())showDir(f.getParentFile());else if(f.isDirectory())showDir(f);else Toast.makeText(this,"Path not found",Toast.LENGTH_SHORT).show();}
 void sortMenu(){String[] a={"Name A-Z","Name Z-A","Size small-large","Size large-small","Modified newest","Modified oldest","Type","Tag","Title","Parts"};new AlertDialog.Builder(this).setTitle("Sort").setItems(a,(d,w)->sortApply(w)).show();}
 void sortApply(int w){File[] fs=current.listFiles();if(fs==null)return;Comparator<File> c;switch(w){case 0:c=Comparator.comparing(File::getName,String.CASE_INSENSITIVE_ORDER);break;case 1:c=Comparator.comparing(File::getName,String.CASE_INSENSITIVE_ORDER).reversed();break;case 2:c=Comparator.comparingLong(File::length);break;case 3:c=Comparator.comparingLong(File::length).reversed();break;case 4:c=Comparator.comparingLong(File::lastModified).reversed();break;case 5:c=Comparator.comparingLong(File::lastModified);break;case 6:c=Comparator.comparing(x->x.getName().contains(".")?x.getName().substring(x.getName().lastIndexOf('.')+1):"");break;case 7:c=Comparator.comparing(x->prefs.getString("tag_"+x.getAbsolutePath(),""),String.CASE_INSENSITIVE_ORDER);break;default:c=Comparator.comparing(File::getName,String.CASE_INSENSITIVE_ORDER);}Arrays.sort(fs,c);list.removeAllViews();for(File f:fs)if(showHidden||!f.getName().startsWith("."))addItem(f);}
 void settings(){String[] a={"Show hidden items","Delete empty folders","Choose USB / HDD"};new AlertDialog.Builder(this).setTitle("Settings").setItems(a,(d,w)->{if(w==0){showHidden=!showHidden;showDir(current);}else if(w==1)deleteEmpty(current);else pickTree();}).show();}
 void deleteEmpty(File r){int n=deleteEmptyRec(r);Toast.makeText(this,"Empty folders removed: "+n,Toast.LENGTH_LONG).show();showDir(current);}int deleteEmptyRec(File f){int n=0;File[]a=f.listFiles();if(a==null)return 0;for(File x:a)if(x.isDirectory()){n+=deleteEmptyRec(x);File[]b=x.listFiles();if(b!=null&&b.length==0&&x.delete())n++;}return n;}
 void delete(File f){new AlertDialog.Builder(this).setTitle("Delete").setMessage(f.getName()).setPositiveButton("Remove",(d,w)->{deleteRec(f);showDir(current);}).setNegativeButton("Cancel",null).show();}void deleteRec(File f){if(f.isDirectory()){File[]a=f.listFiles();if(a!=null)for(File x:a)deleteRec(x);}f.delete();}
 void rename(File f){EditText e=new EditText(this);e.setText(f.getName());new AlertDialog.Builder(this).setTitle("Rename").setView(e).setPositiveButton("Rename",(d,w)->{f.renameTo(new File(f.getParent(),e.getText().toString()));showDir(current);}).setNegativeButton("Cancel",null).show();}
 void tagOne(File f){EditText e=new EditText(this);e.setHint("Tag");e.setText(prefs.getString("tag_"+f.getAbsolutePath(),""));new AlertDialog.Builder(this).setTitle("Tag").setView(e).setPositiveButton("Save",(d,w)->{prefs.edit().putString("tag_"+f.getAbsolutePath(),e.getText().toString().trim()).apply();showDir(current);}).setNegativeButton("Remove",(d,w)->{prefs.edit().remove("tag_"+f.getAbsolutePath()).apply();showDir(current);}).show();}
 void tagSelected(){if(selected.isEmpty()){Toast.makeText(this,"Select files or folders first",Toast.LENGTH_SHORT).show();return;}EditText e=new EditText(this);e.setHint("Tag for all selected items");new AlertDialog.Builder(this).setTitle("Group Tag ("+selected.size()+")").setView(e).setPositiveButton("Apply",(d,w)->{String tag=e.getText().toString().trim();SharedPreferences.Editor ed=prefs.edit();for(File f:selected)ed.putString("tag_"+f.getAbsolutePath(),tag);ed.apply();showDir(current);}).setNegativeButton("Cancel",null).show();}
 void batchRename(){if(selected.isEmpty()){Toast.makeText(this,"Select files or folders first",Toast.LENGTH_SHORT).show();return;}LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);EditText base=new EditText(this);base.setHint("Base name, e.g. Photo");EditText start=new EditText(this);start.setHint("Start number (e.g. 1)");start.setText("1");EditText digits=new EditText(this);digits.setHint("Digits (e.g. 3 → 001)");digits.setText("3");EditText before=new EditText(this);before.setHint("Text before name (optional)");EditText after=new EditText(this);after.setHint("Text after name (optional)");box.addView(base);box.addView(start);box.addView(digits);box.addView(before);box.addView(after);new AlertDialog.Builder(this).setTitle("Advanced Group Rename").setView(box).setPositiveButton("Preview",(d,w)->renamePreview(base.getText().toString(),parseInt(start.getText().toString(),1),parseInt(digits.getText().toString(),3),before.getText().toString(),after.getText().toString())).setNegativeButton("Cancel",null).show();}
 int parseInt(String s,int def){try{return Integer.parseInt(s.trim());}catch(Exception e){return def;}}
 void renamePreview(String base,int start,int digits,String before,String after){if(base.isEmpty())base="Item";ArrayList<String> names=new ArrayList<>();int i=start;for(File f:selected){String ext="";if(!f.isDirectory()){String n=f.getName();int dot=n.lastIndexOf('.');if(dot>0)ext=n.substring(dot);}String num=String.format(Locale.US,"%0"+Math.max(1,digits)+"d",i++);names.add(before+base+"_"+num+after+ext);}StringBuilder sb=new StringBuilder();for(int k=0;k<names.size();k++)sb.append(selected.get(k).getName()).append("  →  ").append(names.get(k)).append("\n");final String preview=sb.toString();new AlertDialog.Builder(this).setTitle("Rename Preview").setMessage(preview).setPositiveButton("Apply",(d,w)->applyBatchRename(names)).setNegativeButton("Cancel",null).show();}
 void applyBatchRename(ArrayList<String> names){HashSet<String> used=new HashSet<>();for(int i=0;i<selected.size();i++){File old=selected.get(i);File target=new File(old.getParent(),names.get(i));if(target.exists()&&!target.equals(old)){new AlertDialog.Builder(this).setTitle("Name conflict").setMessage(target.getName()+" already exists.\nReplace / Skip / Cancel").setPositiveButton("Replace",(d,w)->{deleteRec(target);old.renameTo(target);showDir(current);}).setNeutralButton("Skip",null).setNegativeButton("Cancel",null).show();return;}if(!used.add(target.getAbsolutePath()))continue;old.renameTo(target);}showDir(current);}
 void pickTree(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT_TREE);i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_WRITE_URI_PERMISSION|Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION);startActivityForResult(i,REQ_TREE);}
}
